name: Deploy to VM with Docker Compose

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          # Navigate to the project directory
          cd /opt/luggage-ai
          
          # Pull the latest code with rebase
          git fetch origin
          git rebase origin/main || git rebase origin/master
          
          # Stop existing containers
          docker-compose down || true
          
          # Build and start the services
          docker-compose up -d --build
          
          # Clean up old images and containers
          docker system prune -f
          
          # Show running containers
          docker-compose ps
          
          echo "Deployment completed successfully!"


# Required GitHub Secrets:
# VM_HOST - Your VM's IP address or hostname
# VM_USERNAME - SSH username for your VM
# VM_SSH_KEY - Private SSH key for VM access
